# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32a5fb7349752c1a73762888cff81b4857b90b716f0b5f44faf786176d26e4fe0e478b2ba2c8a039e23d1b9e9a45ebdfe6c3a6359f334d499f3bc7322f2df75

test:
  secret_key_base: 4cbef38c12c8bcd53201bfee385562b1da6d4da59929fd56a8dbf929c420044b32f2bb4b0c984e4f71f281831c86aece0ab9ad1d1bcde289cab862f5c6a7dd86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
